### ISSUE TITLE
Conditional Redirects

### ISSUE THREAD

**Issue by sdlovecraft** [sporto/hop#13]
I can't seem to get a conditional redirect happening with the HOP router.

Attempt 1:  using Hop's in-built navigateTo method.
Problem:  enters never-ending redirection loop which freezes browser.

```
   RoutingAction subAction -> 

      let 

        authToken = model.authModel.authToken 


        ( updatedRouting, fx ) = 

          if not (model.routing.view == Routing.LoginView && isEmpty authToken) then 

            Routing.update (Routing.NavigateTo "/login") model.routing 

          else 

            Routing.update subAction model.routing

      in 

          ( { model | routing = updatedRouting }, Effects.map RoutingAction fx ) 

```
Hop.navigateTo is defined as such, and I can't figure out why this would be entering the never-ending loop that breaks the app.

```

navigateTo : String -> (Effects Action)
navigateTo route =
  route
    |> Url.urlFromUser
    |> navigateToUrl

navigateToUrl : Types.Url -> (Effects Action)
navigateToUrl url =
  url
    |> Url.routeFromUrl
    |> History.setPath
    |> Task.toResult
    |> Task.map GoToRouteResult
    |> Effects.task

```

Attempt 2: send user to the showLogin action inside the Router update method (as if we are navigating there naturally)
```
RoutingAction subAction ->

 

      let 

        authToken = model.authModel.authToken 

        ( updatedRouting, fx ) = 

          if not (model.routing.view == Routing.LoginView && isEmpty authToken) then 

              Routing.update (Routing.ShowLogin loginPayload) model.routing 

          else 

              Routing.update subAction model.routing 

      in 

          ( { model | routing = model.routing }, Effects.map RoutingAction fx ) 
```
Problem: Url in the browser input doesn’t actually change back to ‘/login’, even though the view changes. and we ‘flash’ onto the screen we are being redirected away from.

The relevant case statements inside the Router.update method look like this. I'm using the same patterns as given in the sporto/example-app
```

      NavigateTo path ->
        ( routing, Effects.map HopAction (Hop.navigateTo path) )

      ShowLogin payload ->
        ( { routing | view = LoginView, routerPayload = payload }, Effects.none )


```

Thanks! :)

**Comment by sporto** [comment]
Seems like you never reach "/login" so `model.routing.view == Routing.LoginView` is never true.

`Routing.NavigateTo "/login"` would trigger the action to show the login. But I don't think you are letting that action run its course. You need to allow that action to finish and change `model.routing.view to LoginView`.

**Comment by sdlovecraft** [comment]
Oh, @sporto  I'm a dingus. I didn't realise that I was checking the model values which had yet to be updated to the new route values, entering it into a never-ending loop. What I really need to be checking is the Action payload rather than the model.

Would you do this with a method that 'authenticates' the routing action before it is passed to the update method? Returning a Redirect action if it is not authenticated?

Or would you be more likely to do it inside Routing.update method?

**Comment by sporto** [comment]
I think it should be in Routing.update, in there check if the action is ShowLogin, if so let it update regardless of the authToken

**Comment by sdlovecraft** [comment]
Oh thats a much better idea! Thanks! Still working on getting a nice solution to the authentication redirect problem. I will post here when done incase it might be helpful to someone

**Comment by sporto** [comment]
Closing this as it doesn't seem relevant for Elm 0.17.
