### ISSUE TITLE
Change route and trigger effects at same time

### ISSUE THREAD

**Issue by sdlovecraft** [sporto/hop#14]
I'm wanting to create some kind of routing-middleware, so that I can asynchronously load data before a route loads, and show a loader on the screen.   I cannot figure out how to do this with the HOP router.

My parent level actions look like this:
(I will refer to these as ParentAction)

```
--Actions.elm
.....

import Routing.Actions

type Action
  = NoOp
  | HopAction Hop.Action
  | RoutingAction Routing.Actions.Action
  | AttendancesAction Attendances.Actions.Action
```

Rather than have ShowDashboard change the route, I was planning to attach the ShowDashboard as a payload inside another RoutingAction called ResolveDashboard. This would only be triggered once the Attendances have been loaded.

```
--Routing.Update.elm
.....

update : RoutingAction -> UpdateModel -> ( Router, Effects RoutingAction )
.....

      ShowDashboard payload ->
        let
          fxs =
            [
              Effects.map AttendancesAction (Attendances.Effects.fetchAll authToken)
             , Effects.map RoomsAction (Rooms.Effects.fetchAll authToken)
            ]
              |> Effects.batch
              |> Effects.map (ResolveDashboard)

```
Given that this Effects.batch is of type Effects ParentAction, I am unable to return it from the Routing.update, which expects an Effects RoutingAction to be returned.

```
--Routing.Actions.elm
.....

-- Actions.Action depends on Routing.Actions which depends on Actions.Action etc....

import Actions.Action

type Action
  = HopAction Hop.Action
  | ShowDashboard Hop.Payload
  | ResolveDashboard Effects Actions.Action
```

Furthermore, If I wrap the ParentAction inside the RoutingAction's payload, it creates a circular dependancy.  

I don't see a way out of this. I considered moving the routing middleware logic up to the parent's update method - but it became clear that I cannot trigger an action in a parent's update method, from a Routing.update method that only returns RoutingActions.

**Comment by sporto** [comment]
One alternative is that you don't necessarily need to return a tuple of `( Router, Effects RoutingAction )` in update.

You can make `update` to return a tuple with three things:

```
update : RoutingAction -> UpdateModel -> ( Router, Effects RoutingAction, Effects ParentAction )
	...
	ShowDashboard payload ->
		...
		in
			(model, Effects.none, fx)
```

Then you can handle those in the parent component.

**Comment by yuffiy** [comment]
Do you have some examples about this ?

**Comment by sporto** [comment]
Closing this as it doesn't seem relevant for Elm 0.17.
