### ISSUE TITLE
Document "scroll to top" behavior?

### ISSUE THREAD

**Issue by joshuaclayton** [sporto/hop#15]
I was wondering if outlining "scroll to top" behavior in the documentation would be valuable; if so, I'd be happy to submit a pull request. [I recently implemented this](https://github.com/joshuaclayton/elm-colors/commit/f447d7eba06929b32bb44b22fe94121e9f0df474) with a flag on my model and an outbound port, but if there are other recommendations to how to do this, I'd love to know!

**Comment by sporto** [comment]
This seems quite useful, happy to take a PR with a markdown file for this, or maybe a wiki page. Thanks

**Comment by joshuaclayton** [comment]
@sporto great to hear - I'll send off a PR in the next few days!

**Comment by sporto** [comment]
Closing this as it is inactive.
