### ISSUE TITLE
ERROR  in index.js in full example

### ISSUE THREAD

**Issue by brobrts** [sporto/hop#16]

**Comment by brobrts** [comment]
following the directions I get this when running $ npm run dev.

for what it's worth, I was able to get the basic example and the more complex example from the book running. 

Also, thanks for all of the great stuff - especially the book.

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'elm-webpack' in /Users/williamroberts/Devel/eBooks/spaTutorial/elm-tutorial/code6/hop/examples/full/src
 @ ./src/index.js 8:10-31

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'style-loader' in /Users/williamroberts/Devel/eBooks/spaTutorial/elm-tutorial/code6/hop/examples/full/src
 @ ./src/index.js 3:0-30
ERROR in ./src/index.js

Billy

**Comment by sporto** [comment]
Fixed, added missing deps to package.json
