### ISSUE TITLE
removeQuery does not remove last query parameter

### ISSUE THREAD

**Issue by spektroskop** [sporto/hop#20]
Trying to remove the last query parameter with removeQuery while on / and without a basePath defined does not change the path. This is caused by History.send receiving an empty string which results in an empty path argument to window.history.replaceState. I guess this behaviour is correct for the History module, but it is probably wrong in the context of removeQuery.

The following change seems to solve the issue in my application, although there might be some unintended side effects that I'm unaware of:

[https://github.com/spektroskop/hop/commit/634a4b2d9b4e02ebc2d48e4836ec12acee7d5107]

If this is an acceptable solution I can submit a pull request.

**Comment by sporto** [comment]
I see, good catch, this never occurred to me. Your change looks good, I cannot think of a side effect right now. Happy to take a PR on this, thanks.
