### ISSUE TITLE
How to let the markdown docment <a href="#hot"> work fine with hop

### ISSUE THREAD

**Issue by yuffiy** [sporto/hop#22]
this let router redirect page to NotFound.

Anythings help :)

**Comment by sporto** [comment]
If you are using hash routing then using the hash as anchors will not play well with the router unfortunately. You will need to use path routing or not use anchors.

**Comment by yuffiy** [comment]
@sporto yeap,

has any better way to do this ? like [emberjs](https://github.com/emberjs/ember.js/issues/4098)

**Comment by sporto** [comment]
Can you summarise what Ember does? From reading the initial description of that ticket I think that hop already covers this. i.e. if you use path routing you can use the hash for anchors.
