### ISSUE TITLE
Update for 0.17

### ISSUE THREAD

**Issue by sporto** [sporto/hop#24]
This requires 

https://github.com/Bogdanp/elm-combine
https://github.com/elm-community/elm-history

To be upgraded first

**Comment by fellz** [comment]
elm-combine updated ...

**Comment by sudhirvkumar** [comment]
elm-history is happening...

https://github.com/elm-community/elm-history/tree/0.17

**Comment by domenkozar** [comment]
So If I understand correctly, at some point `elm-lang` will implement `elm-history` so the existing maintainer isn't willing to work on it?

**Comment by sporto** [comment]
@domenkozar 	see https://github.com/elm-community/elm-history/issues/17, it seems elm-lang core will take on this

**Comment by sporto** [comment]
Not the most elegant solution for the user but I'm considering having a version of Hop that asks the user for a port to subscribe. 

As per https://github.com/Bogdanp/elm-route/blob/master/examples/app/index.html

At least until we have a library that offers subscriptions.

**Comment by sudhirvkumar** [comment]
@sporto if you do that... I will jump on it and upgrade my app to Elm 0.17 :+1:

**Comment by sporto** [comment]
http://package.elm-lang.org/packages/elm-lang/navigation/1.0.0/ it out

This lib has a very opinionated way of doing things, it augments Html.App instead of exposing a subscription

I'm not sure what the role of Hop could be (if there is any) with this out. Will play with Navigation first to see where is the value in trying to update Hop.

**Comment by sporto** [comment]
Version 5 released
