### ISSUE TITLE
Query parameters should be encoded

### ISSUE THREAD

**Issue by tko** [sporto/hop#26]
```
> Hop.makeUrlFromLocation
    { basePath = "", hash = True, matchers = [], notFound = False }
    { path = [], query = Dict.singleton "a b&c?d" "1 2&3?4" }
"#/?a b&c?d=1 2&3?4" : String
```
If you then navigate to that URL the query string is completely mangled:
```
{ path = [], query = Dict.fromList [("a b",""),("c","")] }
```

The param name above is pretty contrived, but spaces and special characters in the values should be escaped to be preserved correctly, similar to [Http.url](https://github.com/evancz/elm-http/blob/3.0.1/src/Http.elm#L45).

**Comment by sporto** [comment]
Published 5.0.1 to fix this. Thanks
