### ISSUE TITLE
History / Back Button not working ?

### ISSUE THREAD

**Issue by vankeisb** [sporto/hop#29]
Hello,

I am an Elm noob, and I'm not an SPA-routing expert, so apologies if I ask a silly question. Or maybe ask it in the wrong place, but I could not find a Mailing List or anything for Hop, therefore I'm using the issue tracker.

Is Hop supposed to manage the browser history (back/forward) when navigating ?

I'm using `Navigation.modifyUrl` like in the samples, the url is clearly updated (hash or pushState), but when I hit the back button, there's no entries in the history for the modified urls.

Doesn't seem to work in the distro's basic/full samples neither... Am I missing something (I guess so) ? Did I completely misunderstand the concept behind the router (looks like I did :P) ? 

I thought that `pushState` was precisely about adding entries to the history, so I'm getting a bit confused here.

Advice much appreciated !

Thanks,

Rémi

**Comment by pablohirafuji** [comment]
Hi,

Hop use the [Navigation](http://package.elm-lang.org/packages/elm-lang/navigation/1.0.0/Navigation) package. Instead of using `Navigation.modifyUrl`, use the `Navigation.newUrl` to add a new entry to the browser history. Let me know if works or if I didn't understand the question.

**Comment by vankeisb** [comment]
Hi,

Yep, it works with `newUrl`. My mistake, RTFM... 

Thanks a lot for your prompt response.

Cheers

Rémi

**Comment by sporto** [comment]
I'm reopening this because I should be using `newUrl` in the examples as docs as it is what most expect. Thanks for pointing this out. Will close this issue when done.

**Comment by sporto** [comment]
Done
