### ISSUE TITLE
setQuery doesn't clear the parameters before applying the new parameters

### ISSUE THREAD

**Issue by gdotdesign** [sporto/hop#3]
The query parameters of the URL should be cleared before setting new parameters, consider the following:
* You have set the parameters to `?folderId=0&videoId=1`
* You want to get rid of the `videoId` parameter with `setQuery(Dict.fromList [("folderId", "0")])` because you assume from the name that it sets the query.
* The parameters didn't change.

The fix is easy, the `setQuery` should clear URL parameters before applying the new ones, or there should be a `replaceQuery` function for this behavior.

**Comment by sporto** [comment]
Published `1.2`. This makes `setQuery` works as you expect. Also added `addQuery` which patches the current query.

**Comment by gdotdesign** [comment]
Thanks! :+1: :fireworks:
