### ISSUE TITLE
More flexible matchers

### ISSUE THREAD

**Issue by folkertdev** [sporto/hop#31]
I'm looking for a way to match urls that don't fit the "/name/value/name/value" pattern with Hop. 

[evancz/url-parser](http://package.elm-lang.org/packages/evancz/url-parser/1.0.0/UrlParser) has the functionality to match arbitrary urls, but given Hop's current code, Hop could expose some route parsing primitives based on Combine. Currently, I've hacked together this: 

```elm 
construct2 : (param1 -> param2 -> route) -> String -> Parser param1 -> Parser param2 -> PathMatcher route
construct2 constructor segment1 parser1 parser2 =
    let
        constructor' ( a, b ) =
            constructor a b

        parser =
            Combine.string segment1 *> parser1
                `Combine.andThen` (\r -> 
                    Combine.map (\x -> ( r, x )) (Combine.string "/" *> parser2))
                |> (\p -> p <* Combine.end)
                |> Combine.map constructor'
    in
        { parser = parser
        , segments = [ segment1 ]
        }
``` 

to parse my urls, but it's ugly, not extendable and should (IMO) be wrapped in a package.

Are you planning to make matching arbitrary urls possible? If yes, how can I help?

**Comment by sporto** [comment]
Hi, can you give me some examples of urls you want to match?

**Comment by folkertdev** [comment]
Well, preferably whatever valid url. 

In my specific case, I have

```elm
HomeRoute       "edit/"
DomainRoute     "edit/<domain:string>"
TableRoute      "edit/<domain:string>/<tablename:string>"
EditorRoute     "edit/<domain:string>/<tablename:string>/<id:maybe int>"
```

The problem with the `Maybe Int` can be solved by using two matchers, but these urls have no 
interspersed static strings (like "books"  in "books/<id:int>". They are just the values. 

Depending how how feasible this is, given hops existing infrastructure, I think it would be much nicer if you could mix and match static and parsed segments of a url, like evancz/url-parser.

**Comment by sporto** [comment]
At some point I would like to make Hop more like UrlParser, I like how flexible it is. I will try to get back to this soon.

**Comment by sporto** [comment]
In v6 I decided to just use UrlParser, UrlParser allows to build more flexible matchers.
