### ISSUE TITLE
If elm-lang/navigation is needed for this lib why is it not also a dependency?

### ISSUE THREAD

**Issue by 7sharp9** [sporto/hop#33]
Not sure if this is a stupid question, I know I can simply add the dependency in my elm-package file, but would it not make life easier if the dependency was also included?

**Comment by sporto** [comment]
As far as I know, if I add this `navigation` as dependency of `Hop` you won't be able to import it into your code. Elm will complain that cannot find that module. You need to explictly add it as a dependency of your app to import `navigation`.

I could completly wrap `navigation`, but this doesn't seem a good idea to me. I think having the user require `navigation` directly is better as they could potentially just swap `hop` for something else but still keep all the `navigation` related code.

**Comment by sporto** [comment]
Hi, I will close this as I don't think there is any action to do
