### ISSUE TITLE
version of matchersToPath that accepts list of matchers

### ISSUE THREAD

**Issue by Skinney** [sporto/hop#34]
The current version of `matcherToPath` requires an explicit matcher. To create a for users to do reverse routing (data -> url) one would need to create a new function that pattern matches on the data, and calls `matcherToPath` with the correct matcher.

I don't know if this is possible, but having a version of `matcherToPath` that allows the user to send in a list of matchers, and have the function automagically figure out which matcher is correct for a given type of data, would save a lot of boiler plate.

**Comment by sporto** [comment]
I'm unclear. What would passing a list of matchers do? Thanks

**Comment by Skinney** [comment]
Updated the issue.

**Comment by sporto** [comment]
On the latest version of Hop (v6) decided to use UrlParser instead of my own matchers (UrlParser is more flexible). Because of this there are no reverse routing helpers for now. I will get back to do this when / if I add a reverse routing helper again.
