### ISSUE TITLE
It would be nice if the examples also has a production configuration rather than just dev.

### ISSUE THREAD

**Issue by 7sharp9** [sporto/hop#35]
Its often the way that building in dev is nice and straight forward then you don't know whats the best way and practices fro getting into production.  e.g. I had to check `webpack-dev-middleware` was not production suitable etc.

**Comment by sporto** [comment]
Good point, I will put a note on this on the readme

**Comment by 7sharp9** [comment]
I ended up just using a simple express wrapper, not exactly an express expert mind :-)

**Comment by sporto** [comment]
Added note on this. Thanks.
