### ISSUE TITLE
Layout Management

### ISSUE THREAD

**Issue by joshua1** [sporto/hop#43]
Hi Guys,
How can i handle rendering of the view of my current route in defined parent views or layout (like master pages in asp.net). most routing engine makes provision for defining the layout or parent view where the current route would be rendered

**Comment by sporto** [comment]
You can do it with conditionals, something like

```elm
layoutFor route =
	if route == UserRoute then
		userLayout
	else
		commonLayout
	
view model =
	let
		layout =
			layoutFor model.route
	in
		layout (subView model)
```
