### ISSUE TITLE
Testing for correct order of route matchers

### ISSUE THREAD

**Issue by j-panasiuk** [sporto/hop#44]
This is not much of an issue really, but something that has been bugging me today... Am I missing something obvious here?

Since order in which we define route matchers is important https://github.com/sporto/hop/blob/master/docs/building-routes.md, and natural intuition is to start from top-level routes and then keep adding more nested/specific ones, it is easy to accidentally get it wrong, like:
```elm
matchers =
    [ format DocumentsRoute (s "")
    , format DocumentRoute (int)
    , format DocumentEditRoute (int </> s "edit")
    ]
```
The compiler can't offer any help here, because it just sees a homogeneous list.
So I thought it would be great to have a test, which would scan through the list of matchers and fail if a route would get shadowed by one of its ancestors

As straightforward as it seems, I'm not sure how to get such test to work. Matchers are defined in terms of functions, so comparing them seems very tricky. My idea was to extract parser structure using **toString**, but that doesn't work, as ```toString (int </> s "edit") == "Parser <function>"```
and I don't see a way to transform it from/to more usable data structure.

Any ideas how these parser definitions could be expressed in terms of data which would allow some string represenation (this would also simplify reverse routing)? Or some comparable value, so that we can just use list sorting? Or is this not possible with current API, because of functions-in-model limitations?

**Comment by sporto** [comment]
If what you are after is making sure that the matchers work as expected my suggestion is: 

Create tests that parse urls using your `matchers` and return routes, then assert the returned routes. Something like https://github.com/sporto/hop/blob/master/tests/IntegrationTest.elm#L122

**Comment by j-panasiuk** [comment]
I totally missed these tests in your examples! I was thinking about unit testing matchers for correct order of routes, but this integration test approach solves the problem in a simpler way.

Thanks!
