### ISSUE TITLE
Question about navigateTo

### ISSUE THREAD

**Issue by gdotdesign** [sporto/hop#6]
`elm-history` uses `pushState` to add a new state to the browsers history. It adds it even if the new state is exactly the same as the previous state (this works according to the spec), but I'm thinking this is not the expected behavior in the context of Hop.

The main issue here is whether or not `navigateTo` should check if the current state is equals to the previous state. If it stays how it is now then I suggest adding a new function that does what `navigateTo` does but it would do nothing if the state isn't changed.

**Comment by sporto** [comment]
I agree that navigateTo should check for this and avoid pushing a new state, so I will add this as todo.

Thanks
Sebastian

**Comment by sporto** [comment]
Closing this as it doesn't seem relevant for Elm 0.17. Navigate provides a way of doing this.
