### ISSUE TITLE
Question about encapsulating the router functionality while using effects 

### ISSUE THREAD

**Issue by gusajz** [sporto/hop#7]
Thanks for the great job! This api really makes routing as simple as it should be. :)

I have a question about combining it with effects while encapsulating the router (like in the advanced example).

Suppose I have a route that should show some data from the server depending on a routing parameter. 
For example "comments/2" should fetch comments for the user with id 2 and show them on the screen.

The intuitive solution, I think, would be to return the "Effects Action" in update function for "ShowComments" action.

Something like this (I stripped out a lot of code, I hope it is clear):

```elm
type alias Action = 
  { ShowComments Hop.Payload
  , CommentsAction Comments.Action
  }

update : Action -> Model -> ( Model, Effects Action )
update action model =
  case action of
    ShowComments payload ->
      let
        userId =
          Dict.get "userId" payload.params |> Maybe.withDefault "1" -- The default is just to simplify it.
      in 
        ( { model | currentView = RulesView, routerPayload = payload }
        , Effects.map CommentsAction Comments.getComments
        )
    CommentsAction subAction ->
      let
        ( commentsModel, fx ) =
          Comments.update subAction model.comments
      in
        ( { model | comments = commentsModel }
        , Effects.map CommentsAction fx
        )
        ...

```

Where we have in Comments something like this:

```elm
type alias Action = 
  {
    ...
  }

getComments : String -> Effects Action
...
```
In turn, the http Task will map to a CommentsReceive action that will update the model and then the view will show the new data. Note that since CommentsReceive is a Comments.Action the Main.update function will call Comments.update.

So far, so good. But, suppose I want to split Routing and Main as in the Advaced example.

In Main.elm:
```elm
type alias Action = 
  { CommentsAction Comments.Action
  , RoutingAction Routing.Action
  }

update : Action -> Model -> ( Model, Effects Action )
update action model =
  case action of
    RoutingAction routingAction ->
      ...

    CommentsAction subAction ->
      let
        ( commentsModel, fx ) =
          Comments.update subAction model.comments
      in
        ( { model | comments = commentsModel }
        , Effects.map CommentsAction fx
        )
        ...

```

In Routing.elm:
```elm
type alias Action = 
  { CommentsAction Comments.Action
    ...
  }

update : Action -> Model -> ( Model, Effects Action )
update action model =
  case {- -Debug.log ("Routing.update")- -} action of
    ShowComments payload ->
      let
        userId =
          Dict.get "userId" model.routerPayload.params |> Maybe.withDefault "1" -- The default is just to simplify it.
      in 
        ( { model | currentView = RulesView, routerPayload = payload }
        -- This line is the problem:
        , Effects.map CommentsAction Comments.getComments
        )

    CommentsAction subAction ->
      ...
```

For this to work, I have to duplicate CommentsAction and the handle code (in Main.elm and in Routing.elm).
I mean write this in Main.update and Routing.update: 
```elm
    CommentsAction subAction ->
      let
        ( commentsModel, fx ) =
          Comments.update subAction model.comments
      in
        ( { model | comments = commentsModel }
        , Effects.map CommentsAction fx
        )
```

That defeats the purpose of splitting it in the first place.
I thought initially that maybe it was possible to emit a signal when the route changed, but I had almost the the situation above when I tried it.

This maybe a question more related to Elm Architecture than to HOP. And I am probably missing something, but anyway I think it can make an interesting example.

**Comment by sporto** [comment]
I'm trying to workout this pattern as well, not really sure. I made a repo with something like this https://github.com/sporto/elm-arch-siblings, how one component can talk with a sibling component. I will get back to you.

**Comment by sporto** [comment]
Here is an example with a pattern like this https://github.com/sporto/hop/tree/sibling-effects/Examples/SiblingEffects

- In app there is a mailbox fore receiving the request to load a usre https://github.com/sporto/hop/blob/sibling-effects/Examples/SiblingEffects/App.elm#L50
- Routing send a message to this address https://github.com/sporto/hop/blob/sibling-effects/Examples/SiblingEffects/Routing.elm#L60
- Incoming message are mapped to a Main action https://github.com/sporto/hop/blob/sibling-effects/Examples/SiblingEffects/Routing.elm#L60
- Main then create a user effect to load the user https://github.com/sporto/hop/blob/sibling-effects/Examples/SiblingEffects/Routing.elm#L60

Does this works for you, keen to hear about better ways if you can think of any.

**Comment by gusajz** [comment]
You are right, there is a question about how to talk to a sibling in Elm Architecture.

That totally work, but I have mixed feelings about it. I was evading using a mailbox directly, mostly because it felt too low level for the problem, but maybe there is no other way. What I think that can be a little cumbersome is to have a signal and an action for each page (that needs fetching) defined in App. 

I didn't have the chance to play with this a little more yet, but related particularly to the fetch on routing issue, I was thinking that I can define an onClick event in the page's view to re-fetch the data like this:

```elm
view : Signal.Address Action -> Model -> Html.Html
...
button [ onClick address (LoadUser userId) ] [ text "Refresh!" ]
...
```

Perhaps I am thinking too React-like, but maybe there is a way to define "life-cycle" events in a view pointing to the corresponding "Address Action", the same way the a click does. So we can write an "onLoadView" event that will end up in a LoadUser action, all inside the "User component".

Giving it a second thought, it may be a good idea to remove all the fetching stuff from the page component (Users in this case), make it effect-less (or maybe "dumb") and take care of all the fetching stuff in the App. That would really work with the sibling effects approach.

Only some random thoughts. I will play around a little more with this and get back.

**Comment by sporto** [comment]
Closing this as it doesn't seem to require further action
