### ISSUE TITLE
Routing with validation

### ISSUE THREAD

**Issue by kunjee17** [sporto/hop#8]
Hi, first of I like to thank you for your work on hop and specially on elm-tutorial. It was too good that I gave shout out on twitter even before that got completed. 

I have query here. How, can I provide authentication to routes. Means route /player is available to authenticated users only. Other will move to /login route. 

In other framework they provide some hooks to modify. But I guess thing would be different if I m moving one way. 

It would be great if you can provide some insight or at least in a way I should be going to. 

Great work on HOP btw. :+1:

**Comment by sporto** [comment]
I think that you can do this by putting this logic in the `update` function that gets the route action. For example you can check for authentication and return an effect to go to the login page:

```elm
update : Action -> Model -> (Model, Effects Action)
update action model =
  case action of
    NavigateTo path ->
      (model, Effects.map HopAction (Hop.navigateTo path))
    ShowMain payload ->
      if isAuthenticated(model) then
        ({model | view = Main, routerPayload = payload}, Effects.none)
      else
        (model, NavigateTo "login")
    ...
```

**Comment by kunjee17** [comment]
@sporto thanks.. I guess I got the point. With this method I can put abstraction over it to make it little more general purpose. 

I am closing this issue. :).
